version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    ports:
      - "6000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend11
    ports:
      - "3222:3222"
    environment:
      - PORT=3222
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=new_employee_db
      - DB_PORT=5432
    depends_on:
      - postgres

  frontend:
    build: ./Frontend
    container_name: frontend11
    ports:
      - "7775:80"

  hr_page:
    build: ./Hr_page
    container_name: hr_page11
    ports:
      - "7776:80"
volumes:
  pgdata:

